# Generated by Django 6.0.3 on 2026-03-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('talent', 'Talent'), ('organizer', 'Organizer')], default='talent', max_length=20),
        ),
    ]
