# Generated by Django 6.0.3 on 2026-03-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_event_bookingrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Corporate Event', 'Corporate Event'), ('Birthday Party', 'Birthday Party'), ('Music Festival', 'Music Festival'), ('Private Party', 'Private Party'), ('Charity Gala', 'Charity Gala'), ('Other', 'Other')], max_length=50),
        ),
    ]
