# Generated by Django 6.0.3 on 2026-03-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_talentportfolio_talentmedia_delete_talentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentportfolio',
            name='service_type',
            field=models.CharField(choices=[('singer', 'Singer'), ('dancer', 'Dancer'), ('band', 'Band'), ('dj', 'DJ'), ('emcee', 'Emcee'), ('comedian', 'Comedian'), ('musician', 'Musician'), ('other', 'Other')], max_length=50),
        ),
    ]
