# Generated by Django 6.0.3 on 2026-03-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_alter_talentportfolio_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentmedia',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='talentmedia',
            name='file',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='talentmedia',
            name='media_type',
            field=models.CharField(max_length=50),
        ),
    ]
